### ISSUE TITLE
Slowly for hundreds of samples

### ISSUE THREAD

**Issue by WangKang-Leo** [niaid/EnsMOD#2]
Dear author,

Thank you for developing this wonderful outlier detection tool.

When I input 200 RNA-seq samples, it runs quite slowly even I set K.max as 10. Do you any suggestions on this point?

Best 
Kang

**Comment by manesnp** [comment]
Thanks for your interest in EnsMOD and your kind words.  This code is not multithread, and I'm not surprised that it will take a while to analyze a large dataset.  Unfortunately I don't know how we might speed it up.
